name: torch5080
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - colorama=0.4.6
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - nest-asyncio=1.6.0
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - pywin32=311
  - pyzmq=27.1.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - alembic==1.17.1
      - annotated-types==0.7.0
      - bertopic==0.17.3
      - blis==1.3.0
      - catalogue==2.0.10
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpathlib==0.23.0
      - colorlog==6.10.1
      - confection==0.1.5
      - cymem==2.0.11
      - et-xmlfile==2.0.0
      - filelock==3.20.0
      - fsspec==2025.9.0
      - greenlet==3.2.4
      - hdbscan==0.8.40
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - langcodes==3.5.0
      - language-data==1.3.0
      - llvmlite==0.45.1
      - mako==1.3.10
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.13
      - narwhals==2.10.2
      - networkx==3.5
      - numba==0.62.1
      - numpy==2.3.4
      - openpyxl==3.1.5
      - optuna==4.5.0
      - pandas==2.3.3
      - pillow==12.0.0
      - plotly==6.4.0
      - preshed==3.0.10
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pynndescent==0.5.13
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - shellingham==1.5.4
      - smart-open==7.4.4
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.44
      - srsly==2.5.1
      - stopwords==1.0.2
      - sympy==1.14.0
      - thinc==8.3.7
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.10.0.dev20251106+cu128
      - torchvision==0.25.0.dev20251106+cu128
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.2
      - wrapt==2.0.0
prefix: C:\Users\mhu\miniconda3\envs\torch5080
